name: BUILD

# Controls when the workflow will run
on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:
    branches: [ main ]

jobs:
  build:
    name: Build playlist
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Python 3.8
        uses: actions/setup-python@v1
        with:
          python-version: 3.8

      - name: Generate Playlist
        run: |
          mkdir dist
          python main.py

      - name: Release
        run: |
          set -x
          cd dist
          zip -r ranked-playlist.zip ./*.*
          assets=()
          for asset in ./*.bplist; do
            assets+=("-a" "$asset")
          done
          for asset in ./*.json; do
            assets+=("-a" "$asset")
          done
          assets+=("-a" "ranked-playlist.zip")
          tag_name=`date '+%Y%m%d%H%M'`
          hub release create "${assets[@]}" -m "Latest" "$tag_name"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Cleanup
        uses: dev-drprasad/delete-older-releases@v0.1.0
        with:
          keep_latest: 1
          delete_tags: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}